---
title: "Data Intro and EDA"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(GGally)
library(reshape2)
library(plotly)
```
##1b
```{r}
#make data frames from the txt files
library(dplyr)
library(ggplot2)

images_columns <- c("y", "x","cloud_label","NDAI","SD","CORR","rad_DF","rad_CF",
                    "rad_BF","rad_AF","rad_AN" )
image1 <- read.delim("./image_data/image1.txt", sep="", col.names = images_columns)
image2 <- read.delim("./image_data/image2.txt", sep="", col.names = images_columns)
image3 <- read.delim("./image_data/image3.txt", sep="", col.names = images_columns)
```

```{r}
#calculate percentage of pixels in each class, summarize data
pixel_perc <- function(image){
  n <- nrow(image)
  cloud <- nrow(filter(image, cloud_label==1))
  nocloud <- nrow(filter(image, cloud_label==-1))
  nolabel <- nrow(filter(image, cloud_label==0))
  return(list("cloud"=cloud/n, "no cloud"=nocloud/n, "unlabelled"=nolabel/n))
}

i1_proportions <- pixel_perc(image1)
i2_proportions <- pixel_perc(image2)
i3_proportions <- pixel_perc(image3)
pixels <- data.frame(Image1=unlist(pixel_perc(image1)), Image2=unlist(pixel_perc(image2)), Image3=unlist(pixel_perc(image3)))

pixels
```


```{r}
#images beautiful maps
colors <- c("#56B4E9", "yellow", "#999999")
ggplot(image1,aes(x=x, y=y, fill=factor(cloud_label)))+
  geom_tile()+
  labs(fill= "Cloud?",
        title="Expert Labels")+
  scale_fill_manual(values=colors,
                    labels=c("No Clouds", "Unlabelled", "Clouds"))

ggplot(image2)+
  geom_tile(aes(x=x, y=y, fill=factor(cloud_label)))+
  labs(fill= "Cloud?",
       title="Expert Labels")+
  scale_fill_manual(values=colors,
                    labels=c("No Clouds", "Unlabelled", "Clouds"))

ggplot(image3)+
  geom_tile(aes(x=x, y=y, fill=factor(cloud_label)))+
  labs(fill= "Cloud?",
       title="Expert Labels")+
  scale_fill_manual(values=colors,
                    labels=c("No Clouds", "Unlabelled", "Clouds"))
```

Do we observe some trend/pattern? Is an iid assumption for the samples justified?

An iid assumption for the samples is not justifed, becuase they are not independant. 

```{r}
# quantitative pairwise relationship between features
cormat1 <- round(cor(image1),3)
cormat2 <- round(cor(image2),3)
cormat3 <- round(cor(image3),3)

cormat1
cormat2
cormat3

#I could make these just lower half if that's better
melted_cormat1 <- melt(cormat1)
ggplot(data = melted_cormat1, aes(x=Var1, y=Var2, fill=value)) + 
  geom_tile()+
  ggtitle("Variable Correlation: Image 1")

melted_cormat2 <- melt(cormat2)
ggplot(data = melted_cormat2, aes(x=Var1, y=Var2, fill=value)) + 
  geom_tile()+
  ggtitle("Variable Correlation: Image 2")
```

```{r}
# relationship between NDAI and cloud labels
ggplot(image1, aes(x=cloud_label, y=NDAI)) + 
  geom_violin() + 
  theme_minimal() +
  ggtitle("NDAI and Cloud Label on image1")

ggplot(image2, aes(x=cloud_label, y=NDAI)) + 
  geom_violin() + 
  theme_minimal() +
  ggtitle("NDAI and Cloud Label on image2")

ggplot(image3, aes(x=cloud_label, y=NDAI)) + 
  geom_violin() + 
  theme_minimal() +
  ggtitle("NDAI and Cloud Label on image3")
```

```{r}
# relationship between CORR and cloud labels
ggplot(image1, aes(x=cloud_label, y=CORR)) + 
  geom_violin() + 
  theme_minimal() +
  ggtitle("CORR and Cloud Label on image1")

ggplot(image2, aes(x=cloud_label, y=CORR)) + 
  geom_violin() + 
  theme_minimal() +
  ggtitle("CORR and Cloud Label on image2")

ggplot(image3, aes(x=cloud_label, y=CORR)) + 
  geom_violin() + 
  theme_minimal() +
  ggtitle("CORR and Cloud Label on image3")
```

```{r}
# relationship between SD and cloud labels
ggplot(image1, aes(x=cloud_label, y=SD)) + 
  geom_violin() + 
  theme_minimal() +
  ggtitle("SD and Cloud Label on image1")

ggplot(image2, aes(x=cloud_label, y=SD)) + 
  geom_violin() + 
  theme_minimal() +
  ggtitle("SD and Cloud Label on image2")

ggplot(image3, aes(x=cloud_label, y=SD)) + 
  geom_violin() + 
  theme_minimal() +
  ggtitle("SD and Cloud Label on image3")
```

```{r}
# relationship between rad_DF and cloud labels
ggplot(image1, aes(x=cloud_label, y=rad_DF)) + 
  geom_violin() + 
  theme_minimal() +
  ggtitle("rad_DF and Cloud Label on image1")

ggplot(image2, aes(x=cloud_label, y=rad_DF)) + 
  geom_violin() + 
  theme_minimal() +
  ggtitle("rad_DF and Cloud Label on image2")

ggplot(image3, aes(x=cloud_label, y=rad_DF)) + 
  geom_violin() + 
  theme_minimal() +
  ggtitle("rad_DF and Cloud Label on image3")
```

```{r}
# relationship between rad_CF and cloud labels
ggplot(image1, aes(x=cloud_label, y=rad_CF)) + 
  geom_violin() + 
  theme_minimal() +
  ggtitle("rad_CF and Cloud Label on image1")

ggplot(image2, aes(x=cloud_label, y=rad_CF)) + 
  geom_violin() + 
  theme_minimal() +
  ggtitle("rad_CF and Cloud Label on image2")

ggplot(image3, aes(x=cloud_label, y=rad_CF)) + 
  geom_violin() + 
  theme_minimal() +
  ggtitle("rad_CF and Cloud Label on image3")
```

```{r}
# relationship between rad_BF and cloud labels
ggplot(image1, aes(x=cloud_label, y=rad_BF)) + 
  geom_violin() + 
  theme_minimal() +
  ggtitle("rad_BF and Cloud Label on image1")

ggplot(image2, aes(x=cloud_label, y=rad_BF)) + 
  geom_violin() + 
  theme_minimal() +
  ggtitle("rad_BF and Cloud Label on image2")

ggplot(image3, aes(x=cloud_label, y=rad_BF)) + 
  geom_violin() + 
  theme_minimal() +
  ggtitle("rad_BF and Cloud Label on image3")
```

```{r}
# relationship between rad_AF and cloud labels
ggplot(image1, aes(x=cloud_label, y=rad_AF)) + 
  geom_violin() + 
  theme_minimal() +
  ggtitle("rad_AF and Cloud Label on image1")

ggplot(image2, aes(x=cloud_label, y=rad_AF)) + 
  geom_violin() + 
  theme_minimal() +
  ggtitle("rad_AF and Cloud Label on image2")

ggplot(image3, aes(x=cloud_label, y=rad_AF)) + 
  geom_violin() + 
  theme_minimal() +
  ggtitle("rad_AF and Cloud Label on image3")
```

```{r}
# relationship between rad_AN and cloud labels
ggplot(image1, aes(x=cloud_label, y=rad_AN)) + 
  geom_violin() + 
  theme_minimal() +
  ggtitle("rad_AN and Cloud Label on image1")

ggplot(image2, aes(x=cloud_label, y=rad_AN)) + 
  geom_violin() + 
  theme_minimal() +
  ggtitle("rad_AN and Cloud Label on image2")

ggplot(image3, aes(x=cloud_label, y=rad_AN)) + 
  geom_violin() + 
  theme_minimal() +
  ggtitle("rad_AN and Cloud Label on image3")
```

