---
title: "Diagnostics and Reproducibility"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 4 Diagnostics
Disclaimer: The questions in this section are open-ended. Be visual and quantitative! The gold standard arguments would be able to convince National Aeronautics and Space Administration (NASA) to use your classification method—in which case Bonus points will be awarded.


# (a) Do an in-depth analysis of a good classification model of your choice by showing some diagnostic plots or information related to convergence or parameter estimation.
We could show a partition plot of the QDA, visualizing the boundary with the partimat() function in the 'klaR' package.
If QDA yields two discriminant functions, we could make a scatterplot of the points and compare their classifications. 

Assuming we do soft-SVM and use slacking variables, we could plot the results of the classification model against different values for the slack variable.

Not too sure what to do about convergence, but maybe KNN would be good for that? 

Bias-variance plots?

# office hours quesiton:
what are the cases where lda/qda yield more than one discriminant jfunciton? in a case where you can do a scatter plot and compare the classification predictions.
  not in this case because there are onlt two classes

partition plot of QDA, is this sufficient for 'diagnostic' plot in part 4?
  partition plot, plus other scatter plots 

plotting SVM accuracy with a variety of different slack variables?
  SVM doesnt seem to be working for other people, so we'll probably need to do LDA

What is an example of such a plot for KNN?
  think of how to choose K. and plot the model accuracy for different values of K, as a diagnostic plot?
  

best feature choice; decision stump?
possibility of running PCA on the 5 angles, and creating one super feature to add into training the model

# (b) For your best classification model(s), do you notice any patterns in the misclassification errors? Again, use quantitative and visual methods of analysis. Do you notice problems in particular regions, or in specific ranges of feature values?
Make a prediction-accuracy heat map for this. There's an example for LDA classification in the link below, but I think we could figure out how to apply it to whichever model we use (https://www.displayr.com/linear-discriminant-analysis-in-r-an-introduction/)

# (c) Based on parts 4(a) and 4(b), can you think of a better classifier? How well do you think your model will work on future data without expert labels?
run random forest, or do boosting..

# (d) Do your results in parts 4(a) and 4(b) change as you modify the way of splitting the data?
Gotta make sure we are running the models on both data sets (transformed vs non transformed data)

# (e) Write a paragraph for your conclusion.



## 5 Reproducibility
In addition to a writeup of the above results, please provide a one-line link to a public GitHub repository containing everything necessary to reproduce your writeup. Specifically, imagine that at some point an error is discovered in the three image files, and a future researcher wants to check whether your results hold up with the new, corrected image files. This researcher should be able to easily re-run all your code and produce all your figures and tables. This repository should contain:

(i) The pdf of the report,
(ii) the raw Latex, Rnw or Word used to generate your report,
(iii) your R code (with CVgeneric function in a separate R file),
(iv) a README file describing, in detail, how to reproduce your paper from scratch (assume researcher has access to the images).

 We need two things:
(a) A main pdf report (font size at least 11 pt, less or equal to 12 pages)
generated by Latex, Rnw or Word is required to be submitted to Gradescope.
– Provide top class (research-paper level) writing, useful well-labeled figures and no code in this pdf. Arrange text and figures compactly (.Rnw may not be very useful for this).
– ***You can choose a title for the report and a team name as per your liking (get creative!). Do provide the names and student ID of your teammates below the title.***
– Your report should conclude with an acknowledgment section, where you provide brief discussion about the contributions of each member, and the resources you used, credit all the help you took and briefly outline the way you proceeded with the project.
(b) A link to your GitHub Repo at the end of your write-up that contains all your code (see Section 5 for more details).


#Acknowledgments

contributions of each member:
1 a) Omri b) Phoebe c) Omri
2 a) Phoebe b) Omri c) Omri d) Phoebe
3 a) Omri b) Omri c) *do we want to do the bonus?*
4 a) b) c) d) e)
5 

resources used: 
raaz office hours, professor office hours, ESL textbook, ISL textbook, and the following sites 
http://uc-r.github.io/discriminant_analysis
https://maths-people.anu.edu.au/~johnm/courses/mathdm/2008/pdf/r-exercisesVI.pdf
https://www.displayr.com/linear-discriminant-analysis-in-r-an-introduction/
https://tgmstat.wordpress.com/2014/01/15/computing-and-visualizing-lda-in-r/
https://rpubs.com/ifn1411/LDA
https://stackoverflow.com/questions/20197106/linear-discriminant-analysis-plot-using-ggplot2

brief outline of how we proceeded with the project:


